#favicon: favicon.ico

custom_css:
  navbar:
    height: 64px
    width: auto
    effect: [shadow, floatable, blur]
  sidebar:
    effect: [shadow, blur] # set either floatable or blur
  body:
    effect: [shadow, blur] # [shadow, floatable, blur]
    highlight:
      language: true # show language of codeblock
      copy_btn: true
    text_align: # left, right, justify, center
      h1: left
      h2: left
      h3: left
      h4: left
      p: justify
  fontfamily:
    codefont:
      fontfamily: 'Maple'
      name: 'Maple'
      url: https://cdn.jsdelivr.net/fontsource/fonts/maple-mono@latest/latin-400-normal.woff2
      weight: normal
      style: normal

navbar:
  visible: auto
  logo:
    img:
    icon:
    title: ORLLOW.TOP
  menu:
    - name: 主页
      icon: fa-solid fa-rss
      url: /
    - name: 分类
      icon: fa-solid fa-folder-open
      url: /categories/
    - name: 标签
      icon: fa-solid fa-tags
      url: /tags/
    - name: 归档
      icon: fa-solid fa-archive
      url: /archives/
    - name: 友链
      icon: fa-solid fa-link
      url: /friends/
    - name: 关于
      icon: fa-solid fa-info-circle
      url: /about/
    - name: 夜晚模式
      icon: fas fa-moon
      toggle: darkmode

site_footer:
  layout: [social, license, copyright]
  social:
    - icon: fas fa-envelope
      url: mailto:orangeicepop@orllow.top
    - icon: fab fa-github
      url: https://github.com/Orange-Icepop
  copyright: '[Copyright © Orange-Icepop](/)'

cover:
  title: '橙子冰棒的博客'
  subtitle: 'MC玩家一枚兼发量很大的程序员'
  height_scheme: full
  layout_scheme: focus
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  features:
    - name: 博客
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f4f0.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
      url: /
    - name: 存档
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f5c3.svg # https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f5c3.svg
      url: /archieves/
    - name: LSL
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f516.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f516.svg
      url: https://github.com/Orange-Icepop/LSL

article:
  body:
    top_meta: [author, category, date, counter]
    meta_library:
      author:
        avatar: /images/author.webp
        name: Orange-Icepop
        url: /about/

sidebar:
  position: right # left right
  # 主页、分类、归档等独立页面
  for_page: [blogger, category]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    blogger:
      class: blogger
      display: [desktop]
      avatar: /images/author.webp
      shape: circle
      url: /about/
      title: 橙子冰棒
      subtitle: 普通的中学生，二刺螈，发量充足的程序猿。
      jinrishici: false
      social:
        - icon: fas fa-envelope
          url: mailto:orangeicepop@orllow.top
        - icon: fab fa-github
          url: https://github.com/Orange-Icepop
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fa-solid fa-folder-open
        title: 文章分类
        url: /categories/

comments:
  giscus:
    # 以下配置按照 yml 格式增删填写即可
    repo: Orange-Icepop/BlogDiscussion
    repo-id: R_kgDOQNmj3A
    category: Announcements
    category-id: DIC_kwDOQNmj3M4CxWed
    mapping: "pathname"
    reactions-enabled: "1"
    emit-metadata: "0"
    lang: "zh-CN"
    # 以上配置按照 yml 格式增删填写即可
    theme:
      light: "light" # https://gcore.jsdelivr.net/gh/volantis-x/cdn-volantis@master/css/giscus/light.css
      dark: "dark" # https://gcore.jsdelivr.net/gh/volantis-x/cdn-volantis@master/css/giscus/dark.css

plugins:
  parallax:
    enable: true
    position: cover
    shuffle: false
    images:
      - /images/background.webp
  darkmode:
    enable: true
  code_highlight: highlightjs # highlightjs or prismjs
  # highlight.js
  highlightjs:
    copy_code: true
    # 如果开启以下配置, hexo.config.highlight.enable 需要设置为 false ; hexo.config.highlight.enable 设置为 true, 则以下配置无效
    # # 不再支持 v11.1.0 以下版本
    # js: https://unpkg.com/@highlightjs/cdn-assets@11.5.1/highlight.min.js # Please set hexo.config.highlight.enable = false !!!
    # css: https://unpkg.com/@highlightjs/cdn-assets@11.5.1/styles/default.min.css
    # # # more: https://www.jsdelivr.com/package/npm/@highlightjs/cdn-assets?path=styles

  # prismjs
  # https://prismjs.com/
  # https://hexo.io/zh-cn/docs/syntax-highlight#PrismJS
  prismjs:
    copy_code: true
    # Please set hexo.config.highlight.enable = false !!! set hexo.config.prismjs.enable = true !!!
    js:
      - https://unpkg.com/prismjs/components/prism-core.min.js
      - https://unpkg.com/prismjs/plugins/autoloader/prism-autoloader.min.js
      - https://unpkg.com/prismjs/plugins/line-numbers/prism-line-numbers.min.js
    css:
      - https://unpkg.com/prismjs/themes/prism-dark.css
      - https://unpkg.com/prismjs/plugins/line-numbers/prism-line-numbers.css

category_map:
  硬件: hardware